import { Contract } from "./types";

export const contractsData: Contract[] = [
    {
      id: '1',
      name: 'West Electrical', 
      number: 'C20220420-000001', 
      company: 'Weir',
      type: 'Project', 
      startDate: '4-Mar-2021',
      endDate: '3-Oct-2024',
      status: 'Active',
    },
    {
      id: '2',
      name: 'Construction',
      number: 'CH000002', 
      company: 'Al Nasr Contracting',
      type: 'Recurring', 
      startDate: '9-Aug-2020',
      endDate: '5-Feb-2021',
      status: 'Active',
    },
    {
      id: '3',
      name: 'Small Contract', 
      number: 'CH000003', 
      company: 'Jacobs',
      type: 'Recurring', 
      startDate: '17-May-2021',
      endDate: '26-Oct-2022',
      status: 'Disabled',
    },
    {
      id: '4',
      name: 'Pixaera Test', 
      number: 'CH000004', 
      company: 'Pixaera',
      type: 'Trial', 
      startDate: '6-Oct-2022',
      endDate: '15-Dec-2024',
      status: 'Paused',
    },
    {
      id: '5',
      name: 'Emerge 10 Years', 
      number: 'CH000005', 
      company: 'Emerge Education',
      type: 'Recurring', 
      startDate: '27-Jun-2021',
      endDate: '7-May-2022',
      status: 'Active',
    },
    {
      id: '6',
      name: 'Large Aramco', 
      number: 'CH000006', 
      company: 'Aramco',
      type: 'Recurring', 
      startDate: '5-Feb-2021',
      endDate: '24-Apr-2021',
      status: 'Disabled',
    },
    {
      id: '7',
      name: 'Temporary Contract', 
      number: 'CH000007', 
      company: 'Temporary',
      type: 'Project', 
      startDate: '27-Jun-2020',
      endDate: '11-Sep-2021',
      status: 'Active',
    },
    {
      id: '8',
      name: 'Rio Tinto Test',
      number: 'CH000008', 
      company: 'Rio Tinto',
      type: 'Trial', 
      startDate: '26-Nov-2020',
      endDate: '13-May-2021',
      status: 'Active',
    },
    {
      id: '9',
      name: 'Shell Full',
      number: 'CH000009', 
      company: 'Shell',
      type: 'Recurring', 
      startDate: '9-Jul-2020',
      endDate: '12-Oct-2020',
      status: 'Disabled',
    },

    // ....
  ];